version: '3.8'

services:
  backend:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn home.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - app-data:/app
    depends_on:
      - frontend

  celery:
    build: .
    command: celery -A home worker --loglevel=info
    env_file:
      - .env
    volumes:
      - app-data:/app
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    # ports:
    #   - "80:80"
    expose:
      - "80"

volumes:
  app-data:
